[package]
name = "css"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
common = { path = "../common" }
dom = { path = "../dom" }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
html = { path = "../html" }
