[package]
name = "compositor"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
common = { path = "../common" }
gpu = { path = "../gpu" }
paint = { path = "../paint" }
raster = { path = "../raster" }
thiserror.workspace = true
tiny-skia = "0.11"
tracing.workspace = true
