[package]
name = "raster"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
common = { path = "../common" }
css = { path = "../css" }
layout = { path = "../layout" }
paint = { path = "../paint" }
text-shaping = { path = "../text-shaping" }
thiserror.workspace = true
tiny-skia = "0.11"
tracing.workspace = true

[dev-dependencies]
dom = { path = "../dom" }
html = { path = "../html" }
