[package]
name = "chrome-backend-gpui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
browser-ui = { path = "../browser-ui" }
common = { path = "../common" }
thiserror.workspace = true
tracing.workspace = true
