[package]
name = "browser-shell"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
browser-ui = { path = "../browser-ui" }
chrome-backend-gpui = { path = "../chrome-backend-gpui" }
common = { path = "../common" }
tracing.workspace = true
