[package]
name = "image-decode"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
common = { path = "../common" }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "gif", "ico", "bmp"] }
resvg = "0.44"
thiserror.workspace = true
tiny-skia = "0.11"
tracing.workspace = true
usvg = "0.44"
