[package]
name = "devtools"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
common = { path = "../common" }
css = { path = "../css" }
dom = { path = "../dom" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
storage = { path = "../storage" }
thiserror.workspace = true
tracing.workspace = true
