[package]
name = "soul-backend-gpui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
browser-ui = { path = "../browser-ui" }
common = { path = "../common" }
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit"] }
image = { version = "0.25", default-features = false }
thiserror.workspace = true
tracing.workspace = true
