[package]
name = "soul-backend-gpui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
soul-ui = { path = "../soul-ui" }
common = { path = "../common" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "0ad5441b5370428eaa353a36f63c50c5448eead5" }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "0ad5441b5370428eaa353a36f63c50c5448eead5", features = ["font-kit"] }
image = { version = "0.25", default-features = false }
thiserror.workspace = true
tracing.workspace = true
