[package]
name = "paint"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
common = { path = "../common" }
css = { path = "../css" }
layout = { path = "../layout" }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
dom = { path = "../dom" }
html = { path = "../html" }
