[package]
name = "web-api"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
boa_engine = "0.21.0"
boa_gc = "0.21.0"
common = { path = "../common" }
dom = { path = "../dom" }
javascript = { path = "../javascript" }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
html = { path = "../html" }
