[package]
name = "web-api"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
boa_engine = "0.21.0"
boa_gc = "0.21.0"
common = { path = "../common" }
dom = { path = "../dom" }
javascript = { path = "../javascript" }
storage = { path = "../storage" }
thiserror.workspace = true
tokio = { version = "1", features = ["sync", "macros", "rt-multi-thread"] }
tracing.workspace = true
url = "2.5"

[dev-dependencies]
html = { path = "../html" }
