[package]
name = "browser-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
browser-core = { path = "../browser-core" }
common = { path = "../common" }
storage = { path = "../storage" }
thiserror.workspace = true
tracing.workspace = true
url = "2.5"
