[package]
name = "downloads"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
common = { path = "../common" }
networking = { path = "../networking" }
platform-windows = { path = "../platform-windows" }
storage = { path = "../storage" }
thiserror.workspace = true
tokio = { version = "1", features = ["sync", "io-util", "fs", "macros", "time"] }
tracing.workspace = true
url = "2.5"
